name = "Restrict Markers";
author = "JibStyle";
overview = "Map markers only share to nearby players.";
tooltip = "Restrict Markers";
tooltipOwned = "Restrict Markers - Owned";
picture = "data\Picture.paa";
logo = "data\LogoRed.paa";
logoOver = "data\LogoBlack.paa";
logoSmall = "data\LogoSmallRed.paa";
