name = "Restrict Markers"
author = "JibStyle"
prefix = "jib_marker"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "README.md",
    "LICENSE.md",
    "data/Picture.paa",
    "data/LogoBlack.paa",
    "data/LogoRed.paa",
    "data/LogoSmallRed.paa",
]

[version]
git_hash = 0

